service: lambda-status

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  profile: svc_ocd_buildadmin
  cfLogs: true
  custom: ${file(./config.json)}
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:PutItem
      Resource: { "Fn::Join" : ["", ["arn:aws:dynamodb:us-east-1:*:table/", { "Ref" : "LambdaStatusTable" } ] ]  }

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  handler:
    handler: handler.handler
    timeout: 100
    events:
      - schedule: rate(10 minutes)

resources:
  Resources:
    LambdaStatusTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:provider.custom.stage}-${self:provider.custom.tableName}
          AttributeDefinitions:
            - AttributeName: endpoint
              AttributeType: S
            - AttributeName: timestamp
              AttributeType: N
          KeySchema:
            - AttributeName: endpoint
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  Outputs:
    LambdaStatusTableName:
     Description: "DynamoDb table name"
     Value: { "Ref": "LambdaStatusTable" }